export const CATEGORIES = {
    BUSINESS: 'business',
    ENTERTAINMENT: 'entertainment',
    GENERAL: 'general',
    HEALTH: 'health',
    SCIENCE: 'science',
    SPORTS: 'sports',
    TECHNOLOGY: 'technology',
} as const;

export const CATEGORIES_LABELS = {
    [CATEGORIES.BUSINESS]: 'Business',
    [CATEGORIES.ENTERTAINMENT]: 'Entertainment',
    [CATEGORIES.GENERAL]: 'General',
    [CATEGORIES.HEALTH]: 'Health',
    [CATEGORIES.SCIENCE]: 'Science',
    [CATEGORIES.SPORTS]: 'Sports',
    [CATEGORIES.TECHNOLOGY]: 'Technology',
} as const;

export const LANGUAGES = {
    AR: 'ar',
    DE: 'de',
    EN: 'en',
    ES: 'es',
    FR: 'fr',
    HE: 'he',
    IT: 'it',
    NL: 'nl',
    NO: 'no',
    PT: 'pt',
    RU: 'ru',
    SE: 'se',
    UD: 'ud',
    ZH: 'zh',
} as const;

export const LANGUAGES_LABELS = {
    [LANGUAGES.AR]: 'Arabic',
    [LANGUAGES.DE]: 'German',
    [LANGUAGES.EN]: 'English',
    [LANGUAGES.ES]: 'Spanish',
    [LANGUAGES.FR]: 'French',
    [LANGUAGES.HE]: 'Hebrew',
    [LANGUAGES.IT]: 'Italian',
    [LANGUAGES.NL]: 'Dutch',
    [LANGUAGES.NO]: 'Norwegian',
    [LANGUAGES.PT]: 'Portuguese',
    [LANGUAGES.RU]: 'Russian',
    [LANGUAGES.SE]: 'Swedish',
    [LANGUAGES.UD]: 'Undefined',
    [LANGUAGES.ZH]: 'Chinese',
} as const;

export const COUNTRIES = {
    AE: 'ae',
    AR: 'ar',
    AT: 'at',
    AU: 'au',
    BE: 'be',
    BG: 'bg',
    BR: 'br',
    CA: 'ca',
    CH: 'ch',
    CN: 'cn',
    CO: 'co',
    CU: 'cu',
    CZ: 'cz',
    DE: 'de',
    EG: 'eg',
    FR: 'fr',
    GB: 'gb',
    GR: 'gr',
    HK: 'hk',
    HU: 'hu',
    ID: 'id',
    IE: 'ie',
    IL: 'il',
    IN: 'in',
    IT: 'it',
    JP: 'jp',
    KR: 'kr',
    LT: 'lt',
    LV: 'lv',
    MA: 'ma',
    MX: 'mx',
    MY: 'my',
    NG: 'ng',
    NL: 'nl',
    NO: 'no',
    NZ: 'nz',
    PH: 'ph',
    PL: 'pl',
    PT: 'pt',
    RO: 'ro',
    RS: 'rs',
    RU: 'ru',
    SA: 'sa',
    SE: 'se',
    SG: 'sg',
    SI: 'si',
    SK: 'sk',
    TH: 'th',
    TR: 'tr',
    TW: 'tw',
    UA: 'ua',
    US: 'us',
    VE: 've',
    ZA: 'za',
} as const;

export const COUNTRIES_LABELS = {
    [COUNTRIES.AE]: 'United Arab Emirates',
    [COUNTRIES.AR]: 'Argentina',
    [COUNTRIES.AT]: 'Austria',
    [COUNTRIES.AU]: 'Australia',
    [COUNTRIES.BE]: 'Belgium',
    [COUNTRIES.BG]: 'Bulgaria',
    [COUNTRIES.BR]: 'Brazil',
    [COUNTRIES.CA]: 'Canada',
    [COUNTRIES.CH]: 'Switzerland',
    [COUNTRIES.CN]: 'China',
    [COUNTRIES.CO]: 'Colombia',
    [COUNTRIES.CU]: 'Cuba',
    [COUNTRIES.CZ]: 'Czech Republic',
    [COUNTRIES.DE]: 'Germany',
    [COUNTRIES.EG]: 'Egypt',
    [COUNTRIES.FR]: 'France',
    [COUNTRIES.GB]: 'United Kingdom',
    [COUNTRIES.GR]: 'Greece',
    [COUNTRIES.HK]: 'Hong Kong',
    [COUNTRIES.HU]: 'Hungary',
    [COUNTRIES.ID]: 'Indonesia',
    [COUNTRIES.IE]: 'Ireland',
    [COUNTRIES.IL]: 'Israel',
    [COUNTRIES.IN]: 'India',
    [COUNTRIES.IT]: 'Italy',
    [COUNTRIES.JP]: 'Japan',
    [COUNTRIES.KR]: 'South Korea',
    [COUNTRIES.LT]: 'Lithuania',
    [COUNTRIES.LV]: 'Latvia',
    [COUNTRIES.MA]: 'Morocco',
    [COUNTRIES.MX]: 'Mexico',
    [COUNTRIES.MY]: 'Malaysia',
    [COUNTRIES.NG]: 'Nigeria',
    [COUNTRIES.NL]: 'Netherlands',
    [COUNTRIES.NO]: 'Norway',
    [COUNTRIES.NZ]: 'New Zealand',
    [COUNTRIES.PH]: 'Philippines',
    [COUNTRIES.PL]: 'Poland',
    [COUNTRIES.PT]: 'Portugal',
    [COUNTRIES.RO]: 'Romania',
    [COUNTRIES.RS]: 'Serbia',
    [COUNTRIES.RU]: 'Russia',
    [COUNTRIES.SA]: 'Saudi Arabia',
    [COUNTRIES.SE]: 'Sweden',
    [COUNTRIES.SG]: 'Singapore',
    [COUNTRIES.SI]: 'Slovenia',
    [COUNTRIES.SK]: 'Slovakia',
    [COUNTRIES.TH]: 'Thailand',
    [COUNTRIES.TR]: 'Turkey',
    [COUNTRIES.TW]: 'Taiwan',
    [COUNTRIES.UA]: 'Ukraine',
    [COUNTRIES.US]: 'United States',
    [COUNTRIES.VE]: 'Venezuela',
    [COUNTRIES.ZA]: 'South Africa',
} as const;
